version: 2.1

orbs:
  ruby: circleci/ruby@1.1.3

jobs:
  build:
    docker:
      - image: 'cimg/ruby:2.4.10'
    steps:
      - checkout
      - ruby/install:
          version: '2.6.7'
      - run: echo "Ruby 2.6.7 has been installed"
      - run: ruby -v

workflows:
  run-jobs:
    jobs:
      - build

