version: 2.1

orbs:
  ruby: circleci/ruby@1.1.3

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - ruby/install:
          version: '2.3.8'
      - run: echo "Ruby 2.3.8 has been installed"
      - run: ruby -v

workflows:
  run-jobs:
    jobs:
      - build
