version: 2.1

orbs:
  ruby: circleci/ruby@1.1.3

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - ruby/install:
          version: '2.4.1'
      - run: echo "Ruby 2.4.1 has been installed"
      - run: ruby -v

workflows:
  run-jobs:
    jobs:
      - build

